name: Build PHP Web Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install dependencies
        run: composer install

      - name: Build PHP web page
        run: php build.php

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: /var/www/html
